export const CARD_BG_1 = 'https://ik.imagekit.io/euurqxbuc/uploaded-asset_Apa0r-9Nn?tr=orig-true'
export const CARD_BG_2 = 'https://ik.imagekit.io/euurqxbuc/uploaded-asset_mnwzwAsLy?tr=orig-true'
export const BOLT_ICON = 'https://ik.imagekit.io/euurqxbuc/uploaded-asset_b7rpiQA2t?tr=orig-true'
export const BG_PAGE_1 = 'https://ik.imagekit.io/euurqxbuc/uploaded-asset_tjcicCPkH?tr=orig-true'
export const BG_PAGE_2 = 'https://ik.imagekit.io/euurqxbuc/uploaded-asset_TJOXzrU4i?tr=orig-true'
